[package]
name = "weblog-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-files = "0.6" # For serving static files 
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" # For handling JSON requests
tera = "1.0"
